apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceclass-controller
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["snowflying.io"]
  resources: ["namespaceclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
